name: atomix_design_flutter
description: A modern Flutter Design System with Atomic Design and Material 3. Includes theming, reusable components, and documentation.
version: 0.3.0
repository: https://github.com/OsmanJimenez/atomix_design_flutter
homepage: https://github.com/OsmanJimenez/atomix_design_flutter
issue_tracker: https://github.com/OsmanJimenez/atomix_design_flutter/issues

environment:
  sdk: ^3.10.7
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - design-system
  - atomic-design
  - material-design
  - ui-components
  - theme

flutter:
